[package]
name = "snowhash_wasm"
version = "0.1.0"
authors = ["Josh Leeb-du Toit <mail@joshleeb.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.55"
serde_derive = "1.0.55"
serde_json = "1.0.17"
snowhash = { path = "../" }
wasm-bindgen = "0.2.4"
